Repository ProjectSakura/maintainers, pull requests merged in 2021-04, with the labels that each got.

#2 code base restructured
  .gitignore
  README.md
  frontend/.gitignore
  frontend/README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
Labels: gssoc21, level1

#3 Added licence and SEO and icon package
  license
  package.json
  public/icons/android-chrome-192x192.png
  public/icons/android-chrome-512x512.png
  public/icons/apple-touch-icon.png
  public/icons/browserconfig.xml
  public/icons/favicon-16x16.png
  public/icons/favicon-32x32.png
  public/icons/favicon.ico
  public/icons/mstile-150x150.png
  public/icons/safari-pinned-tab.svg
  public/icons/site.webmanifest
  public/index.html
Labels: gssoc21, level2

#5 Created PR and Issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: gssoc21, level3

#4 contributors page added
  package-lock.json
  package.json
  src/App.js
  src/components/contributors/contributors.js
  src/components/contributors/contributors.module.css
  src/components/contributors/data.js
  src/index.js
Labels: gssoc21, level3

#6 footer added
  src/App.js
  src/components/Footer/footer.js
  src/components/Footer/footer.module.css
  src/components/Footer/sakura_footer.svg
Labels: gssoc21, level3
